In [1]:
import yfinance as yf
import requests
import pandas as pd
import datetime as dt
import time
from datetime import timedelta
from prod.model import *
from functools import reduce
from yahoo_fin import stock_info as si
import numpy as np
import gspread
import pandas as pd
from oauth2client.service_account import ServiceAccountCredentials
import pygsheets

In [2]:
# inversion inicial en dolares
#initial_amount=5249000/777.18
initial_amount=5000000/777.18

# ponderacion del portafolio
ponderacion={'ETHO':4.6/100,
'ESGV':4.12/100,
'VT':12.16/100,
'XLK':15.16/100,
'VTI':19.61/100,
'IVV':11.42/100,
'QQQ':15.30/100,
'ESGU':4.79/100,
'SMH':6.72/100,
'ARKW':2.30/100,
'ARKK':2.13/100,
'OTROS':2.23/100}

# portafolio en el que se invierte
tickers=["ESGV","ETHO","VT","XLK","VTI","IVV","QQQ","SMH","ARKW","ARKK","ESGU"]

In [3]:
dataframes=[]
for i in tickers:
       
    # Generamos el diccionario pada cada ticker
    string="{i}=ticker('{i}')".format(i=i)
    exec(string)
    
    string2="df_{i}={i}.getLatest()".format(i=i)
    exec(string2)
    
    string3="df_{i}['ticker']='{i}'".format(i=i)
    exec(string3)
    
    string4="dataframes.append(df_{i})".format(i=i)
    exec(string4)

# Concatenamos todos los dataframes en solo uno
day_display=reduce(lambda x, y: pd.concat([x, y]), dataframes)
day_display

08/13/2020
Creating ticker ...
ESGV was created, date:08/13/2020
08/13/2020
Creating ticker ...
ETHO was created, date:08/13/2020
08/13/2020
Creating ticker ...
VT was created, date:08/13/2020
08/13/2020
Creating ticker ...
XLK was created, date:08/13/2020
08/13/2020
Creating ticker ...
VTI was created, date:08/13/2020
08/13/2020
Creating ticker ...
IVV was created, date:08/13/2020
08/13/2020
Creating ticker ...
QQQ was created, date:08/13/2020
08/13/2020
Creating ticker ...
SMH was created, date:08/13/2020
08/13/2020
Creating ticker ...
ARKW was created, date:08/13/2020
08/13/2020
Creating ticker ...
ARKK was created, date:08/13/2020
08/13/2020
Creating ticker ...
ESGU was created, date:08/13/2020

,date,open,high,low,last_price,change,price_change,ticker
0,2020-08-13,61.840000,61.985001,61.709999,61.849998,0.016168,0.009998,ESGV
0,2020-08-13,44.810001,44.931198,44.810001,44.889999,0.178527,0.079998,ETHO
0,2020-08-13,81.699997,81.980003,81.690002,81.834999,0.165241,0.135002,VT
0,2020-08-13,114.070000,114.910004,113.800003,114.330002,0.227932,0.260002,XLK
0,2020-08-13,170.789993,171.744995,170.789993,171.413406,0.365017,0.623413,VTI
0,2020-08-13,338.000000,339.614990,337.809998,338.980011,0.289944,0.980011,IVV
0,2020-08-13,272.640015,274.829987,272.390015,273.459290,0.300497,0.819275,QQQ
0,2020-08-13,172.410004,172.589996,170.850006,171.270004,-0.661214,-1.139999,SMH
0,2020-08-13,99.150002,100.345001,98.922401,99.739304,0.594354,0.589302,ARKW
0,2020-08-13,84.510002,86.389999,84.510002,85.705597,1.414738,1.195595,ARKK
0,2020-08-13,76.510002,76.839996,76.430000,76.680000,0.222191,0.169998,ESGU

In [4]:
# agregamos una columna de ponderacion de cada instrumento
day_display["pond"]=day_display["ticker"].apply(lambda x: ponderacion.get(x))

# Extraemos los montos que no tuvieron pnderacion
not_considered_per=1-sum(day_display["pond"])

# Guardamos lo que no se invirtio.. no se considera en la estimacion
rest=initial_amount*not_considered_per
invested=initial_amount-rest

# Agregamos columnas de cantidad inicial invertida y no invertida independiente del fondo
day_display["initial_invested_usd"]=initial_amount
day_display["real_invested"]=invested
day_display["not_invested"]=rest

# Calculamos lo que se invirtio en cada instrumento
day_display["invested"]=day_display["pond"].apply(lambda x: x*initial_amount)

# Calculamos las ganancias o perdidas
day_display["profit"]=(day_display["change"]/100)*(day_display["invested"])

# Calculamos el nuevo valor de la cantidad invertida en el instrumento 
day_display["estimated"]=day_display["invested"]+day_display["profit"]

# Agregamos una columna con el resultado final de lo invertido
day_display['total_result']=sum(day_display["estimated"])-sum(day_display["invested"])

In [5]:
day_display

,date,open,high,low,last_price,change,price_change,ticker,pond,initial_invested_usd,real_invested,not_invested,invested,profit,estimated,total_result
0,2020-08-13,61.840000,61.985001,61.709999,61.849998,0.016168,0.009998,ESGV,0.0412,6433.516045,6324.789624,108.726421,265.060861,0.042855,265.103716,14.424404
0,2020-08-13,44.810001,44.931198,44.810001,44.889999,0.178527,0.079998,ETHO,0.0460,6433.516045,6324.789624,108.726421,295.941738,0.528336,296.470074,14.424404
0,2020-08-13,81.699997,81.980003,81.690002,81.834999,0.165241,0.135002,VT,0.1216,6433.516045,6324.789624,108.726421,782.315551,1.292708,783.608259,14.424404
0,2020-08-13,114.070000,114.910004,113.800003,114.330002,0.227932,0.260002,XLK,0.1516,6433.516045,6324.789624,108.726421,975.321032,2.223070,977.544102,14.424404
0,2020-08-13,170.789993,171.744995,170.789993,171.413406,0.365017,0.623413,VTI,0.1961,6433.516045,6324.789624,108.726421,1261.612496,4.605104,1266.217601,14.424404
0,2020-08-13,338.000000,339.614990,337.809998,338.980011,0.289944,0.980011,IVV,0.1142,6433.516045,6324.789624,108.726421,734.707532,2.130241,736.837773,14.424404
0,2020-08-13,272.640015,274.829987,272.390015,273.459290,0.300497,0.819275,QQQ,0.1530,6433.516045,6324.789624,108.726421,984.327955,2.957875,987.285830,14.424404
0,2020-08-13,172.410004,172.589996,170.850006,171.270004,-0.661214,-1.139999,SMH,0.0672,6433.516045,6324.789624,108.726421,432.332278,-2.858642,429.473636,14.424404
0,2020-08-13,99.150002,100.345001,98.922401,99.739304,0.594354,0.589302,ARKW,0.0230,6433.516045,6324.789624,108.726421,147.970869,0.879471,148.850340,14.424404
0,2020-08-13,84.510002,86.389999,84.510002,85.705597,1.414738,1.195595,ARKK,0.0213,6433.516045,6324.789624,108.726421,137.033892,1.938670,138.972562,14.424404
0,2020-08-13,76.510002,76.839996,76.430000,76.680000,0.222191,0.169998,ESGU,0.0479,6433.516045,6324.789624,108.726421,308.165419,0.684715,308.850134,14.424404

In [6]:
def save_gsheets(page,dataframe):
    gc = pygsheets.authorize(service_file='key.json')

    #open the google spreadsheet 
    sh = gc.open_by_url('https://docs.google.com/spreadsheets/d/1z7zzHgM6t4ySUkPZe5BdFsBvTD6RxsfSdKEnqWU1a2Q/edit#gid=67598709')

    #select the first sheet 
    wks = sh[page]

    #update the first sheet with df, starting at cell B2. 
    wks.set_dataframe(dataframe, 'A1')

In [7]:
save_gsheets(0,day_display)